description: |-
  This playbook contains the phases for handling an incident as they are described in the SANS Institute ‘Incident Handler's Handbook’ by Patrick Kral.

  https://www.sans.org/reading-room/whitepapers/incident/incident-handlers-handbook-33901

  ***Disclaimer: This playbook does not ensure compliance to SANS regulations.
id: SANS - Incident Handler's Handbook Template
inputs: []
name: SANS - Incident Handler's Handbook Template
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: b96d4039-2dd2-4036-89ac-2d9433c9d4ac
      iscommand: false
      name: ""
      version: -1
    taskid: b96d4039-2dd2-4036-89ac-2d9433c9d4ac
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        "This phase deals with preparing a team to be ready to handle an incident at a moment’s notice.
        The incident preparation is the most crucial phase compared to all of the others, as
        it will determine how well your team will be able to respond in the event of a crises."
      id: 01649a7d-0936-4979-80a3-80853a2cc026
      iscommand: false
      name: Preparation
      type: regular
      version: -1
    taskid: 01649a7d-0936-4979-80a3-80853a2cc026
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        "Provides a written set of principles, rules, or practices within an organization;
        it is one of the keystone elements that provide guidance as to whether an incident has occurred in an organization.
        Without clear policies, one could leave their organization legally vulnerable to law suits."
      id: 6bd0d519-7244-4c4f-8577-b2d4247c2dcb
      iscommand: false
      name: a. Policy
      type: regular
      version: -1
    taskid: 6bd0d519-7244-4c4f-8577-b2d4247c2dcb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        "After establishing organizational policies, now it is time to create a plan/strategy to handle incidents. Prioritization of incidents should be based upon organizational impact.

        The prioritization of the types of incidents based upon organizational impact can
        help build the case to receive management buy-in, because without management support then it is likely that the CIRT may not be given the resources necessary to properly handle a crisis."
      id: 141140d9-1b1c-4f7f-8fd8-d0472f955251
      iscommand: false
      name: b. Response Plan/Strategy
      type: regular
      version: -1
    taskid: 141140d9-1b1c-4f7f-8fd8-d0472f955251
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        "Having a communication plan is necessary, due to the fact that it may be necessary to contact specific individuals during an incident. The entire CIRT should know whom to contact, when it is appropriate to contact them, and why.
        By not having a communications plan, then it is likely that response time will be delayed and/or the wrong people would be contacted and one would not have the proper resources necessary to mitigate the problem.

        It is also necessary to define when it is or is not appropriate to include law enforcement during an incident, due to the consequences that could either positively or negatively affect your organization."
      id: 864febe5-a0f8-40a8-8f9e-a5e89cce505f
      iscommand: false
      name: c. Communication
      type: regular
      version: -1
    taskid: 864febe5-a0f8-40a8-8f9e-a5e89cce505f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: "\"This element is particularly necessary and can be a substantial
        life saver when it comes to incident response. \nThe most significant reason
        to document an incident is that if the incident is considered a\ncriminal
        act, then it could be used as evidence to bring the suspect(s) to justice.
        The other\nreason for documentation that is just as important is for lessons
        learned.\n\nIt is vital that everything that is done by the CIRT team is documented,
        that means every action taken (e.g. commands typed, systems affected, etc).
        Documentation should be able to answer the Who, What, When, Where, Why, and
        How questions should they ever arise; \""
      id: 07d61400-ab92-4aa0-83a8-a50653cdcc12
      iscommand: false
      name: d. Documentation
      type: regular
      version: -1
    taskid: 07d61400-ab92-4aa0-83a8-a50653cdcc12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        "The CIRT should be made up of several people that consist of different disciplines
        to handle the various problems that could arise during or from an incident."
      id: f3474c01-1ec2-480c-8633-a3555183c71d
      iscommand: false
      name: e. Team
      type: regular
      version: -1
    taskid: f3474c01-1ec2-480c-8633-a3555183c71d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: '"Ensure that the CIRT can have the appropriate permissions necessary
        to perform their job."'
      id: ed34fe2e-e077-481c-80f4-77b4b69f25e8
      iscommand: false
      name: f. Access Control
      type: regular
      version: -1
    taskid: ed34fe2e-e077-481c-80f4-77b4b69f25e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: "\"It is highly recommended having any available software and hardware
        that can be readily utilized during an incident; this can range from anti-malware
        to laptops with packets sniffers, screw drivers and other tools, as well as
        incident response checklists and other items that would be useful. \nAll of
        the tools one would need during an incident should be contained within a “jump
        bag” that can be quickly grabbed by CIRT members during an incident.\""
      id: d80874f7-ea94-4418-8ab7-4c60db11f2f9
      iscommand: false
      name: g. Tools
      type: regular
      version: -1
    taskid: d80874f7-ea94-4418-8ab7-4c60db11f2f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1565
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: '"It is recommended to have drills at regular interval to insure
        that each individual within the CIRT is able or knows how to perform their
        duties during an incident."'
      id: 6f3d679e-2435-418e-883c-f001a05b055a
      iscommand: false
      name: h. Training
      type: regular
      version: -1
    taskid: 6f3d679e-2435-418e-883c-f001a05b055a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1740
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 8679f3c7-9a65-4f37-88d2-c823f8ad506d
      iscommand: false
      name: Preparation
      type: title
      version: -1
    taskid: 8679f3c7-9a65-4f37-88d2-c823f8ad506d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 34d3ba7c-8f9b-4695-8ec8-2d7fa0f5d996
      iscommand: false
      name: Identification
      type: title
      version: -1
    taskid: 34d3ba7c-8f9b-4695-8ec8-2d7fa0f5d996
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1915
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: "\"This phase deals with the detection and determination of whether
        a deviation from normal operations within an organization is an incident,
        and its scope assuming that the deviation is indeed an incident. \n\nThis
        particular step requires one to gather events from various sources such\nas
        log files, error messages, and other resources, such intrusion detection systems
        and firewalls, that may produce evidence as to determine whether an event
        is an incident. If a particular event is determine to be an incident, and
        then it should be reported as soon as possible in order to allow the CIRT
        enough time to collect evidence and prepare for the preceding steps.\n\nThis
        is also the phase where incident responders should be documenting everything
        that they are doing, as stated earlier these documents should be able to answer
        the Who, What, Where, Why, and How questions.\""
      id: e9ed4238-421d-4163-8cfb-91a5925dc313
      iscommand: false
      name: Identification
      type: regular
      version: -1
    taskid: e9ed4238-421d-4163-8cfb-91a5925dc313
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2060
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 075356b5-6397-4496-809d-99c4f0aa8c27
      iscommand: false
      name: Containment
      type: title
      version: -1
    taskid: 075356b5-6397-4496-809d-99c4f0aa8c27
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2235
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |+
        "The primary purpose of this phase is to limit the damage and prevent any further damage from happening.  There are several steps to this phase;

        The first step is Short-term Containment; basically the focus of this step is to limit the damage as soon as possible. Short-term containment is not intended to be a long term
        solution to the problem; it is only intended to limit the incident before it gets worse.

        The second step is System Back-Up; it is necessary before wiping and reimaging any system to take a forensic image of the affected system(s) with tools that are well known in the computer forensics community. The reason behind this is that the forensic software will capture the affected system(s) as they were during the incident and
        thereby preserving evidence in the event that the incident resulted from a criminal act or to be used for observing how the system(s) were compromised during the lessons learned phase.

        The last step before the next phase is Long-term containment, which is essentially the step where the affected systems can be temporarily fix in order to allow them to continue to be used in production, if necessary, while rebuilding clean systems in the next phase."

      id: df879e15-0d82-4733-8663-eb1029f5ed0f
      iscommand: false
      name: Containment
      type: regular
      version: -1
    taskid: df879e15-0d82-4733-8663-eb1029f5ed0f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2380
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 3dd23024-7757-464b-82a6-3acdfeda4f5a
      iscommand: false
      name: Eradication
      type: title
      version: -1
    taskid: 3dd23024-7757-464b-82a6-3acdfeda4f5a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2555
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |
        "This phase deals with the actual removal and restoration of affected systems. As with each of the prior phases of incident response, continued documentation of all actions taken will be necessary to determine the cost of man hours and other resources as a means of determining the overall impact to the organization.
        It is also necessary to ensure that proper steps were taken to remove malicious and other illicit content off of the affected systems, and ensuring that they are thoroughly clean.

        This phase is also the point where defenses should be improved after learning what caused the incident and ensure that the system cannot be compromised again."
      id: 3788bdf3-4387-4832-8e1e-ff562a6d42d1
      iscommand: false
      name: Eradication
      type: regular
      version: -1
    taskid: 3788bdf3-4387-4832-8e1e-ff562a6d42d1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2700
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 375681e5-d6d1-4f6a-8d7d-e9c7556de299
      iscommand: false
      name: Recovery
      type: title
      version: -1
    taskid: 375681e5-d6d1-4f6a-8d7d-e9c7556de299
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2875
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: '"The purpose of this phase is to bring affected systems back into
        the production environment carefully, as to insure that it will not lead another
        incident. It is essential to test, monitor, and validate the systems that
        are being put back into production to verify that they are not being reinfected
        by malware or compromised by some other means."'
      id: abf33f5d-086f-4642-85f5-a086f53e3fe9
      iscommand: false
      name: Recovery
      type: regular
      version: -1
    taskid: abf33f5d-086f-4642-85f5-a086f53e3fe9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3020
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: e077c579-9ccb-4332-860f-032ea715eea8
      iscommand: false
      name: Lessons Learned
      type: title
      version: -1
    taskid: e077c579-9ccb-4332-860f-032ea715eea8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3195
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: "\"The purpose of this phase is to complete any documentation that
        was not done during the incident, as well as any additional documentation
        that may be beneficial in future incidents. \nThe document should also be
        written in a form of a report to provide a play-by-play review of the entire
        incident; this report should be able to answer the: Who, What, Where, Why,
        and How questions that may come up during the lessons learned meeting. \nThe
        overall goal is to learn from the incidents that occurred within an organization
        to improve the team’s performance and provide reference materials in the event
        of a\nsimilar incident. \nThe lessons learned meeting should be performed
        as soon as possible\""
      id: 352cfbaa-4291-4d6b-801b-dbc7812a292a
      iscommand: false
      name: Lessons Learned
      type: regular
      version: -1
    taskid: 352cfbaa-4291-4d6b-801b-dbc7812a292a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3340
        }
      }
  "21":
    id: "21"
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ""
      id: b7682c17-e347-442f-8df2-0e31edc99874
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b7682c17-e347-442f-8df2-0e31edc99874
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3515
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3530,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
