id: b58cc3ec-b9d1-4acb-840d-168da378b92e
inputs: []
name: report
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: dea2c839-4cbc-4c39-8f05-b4bb32a58e76
      iscommand: false
      name: ""
      version: -1
    taskid: dea2c839-4cbc-4c39-8f05-b4bb32a58e76
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    scriptarguments:
      incidentId: {}
      name: {}
      type: {}
    separatecontext: false
    task:
      brand: ""
      description: |-
        A script to generate investigation summary report in an automated way
        Can be used in post-processing flow as well.
      id: e7fdf230-97c0-4f04-843c-00127d05b915
      iscommand: false
      name: Untitled Task
      script: GenerateInvestigationSummaryReport
      type: regular
      version: -1
    taskid: e7fdf230-97c0-4f04-843c-00127d05b915
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 225,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
