description: This playbook provides a manual alternative to the IT - Employee Offboarding
  playbook. The playbook guides the user in the process of manually offboarding an
  employee.
id: IT - Employee Offboarding - Manual
inputs: []
name: IT - Employee Offboarding - Manual
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 0b0f08ec-4006-49c8-8d0a-22dd2bcd7347
      iscommand: false
      name: ""
      version: -1
    taskid: 0b0f08ec-4006-49c8-8d0a-22dd2bcd7347
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        Gather user information that will be needed for the offboarding process.
        Important information may be:
        - Full name of the employee
        - Email address of the employee
        - Employee's phone number(s)
        - Username(s) of the employee
        - Employee's Password(s)
        - Employee's manager's phone number and email address
        - Company property in employee's possession
      id: fff60c22-bcc4-484c-8366-c45423b8dc07
      iscommand: false
      name: Gather user information & property
      type: regular
      version: -1
    taskid: fff60c22-bcc4-484c-8366-c45423b8dc07
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 0678f806-9b12-46f7-83b0-a5d05df44b5c
      iscommand: false
      name: Security - Revoke Permissions
      type: title
      version: -1
    taskid: 0678f806-9b12-46f7-83b0-a5d05df44b5c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: If the employee has a mobile device from the company, disassociate
        the user's mobile device from the user account. If possible, wipe any company-related
        information from the device (such as G-Suite account data which is tied to
        the company).
      id: 776a1525-531d-4d3c-8169-8a9c92b77582
      iscommand: false
      name: Disable company mobile device & company login data
      type: regular
      version: -1
    taskid: 776a1525-531d-4d3c-8169-8a9c92b77582
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -290,
          "y": 720
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Deactivate the user in multi-factor authentication applications,
        such as Okta.
      id: c4c34292-b44a-43a5-87b2-85d2eb0bb7fc
      iscommand: false
      name: Deactivate user in MFA applications
      type: regular
      version: -1
    taskid: c4c34292-b44a-43a5-87b2-85d2eb0bb7fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 720
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: If the user has any admin roles in any application, make sure to
        revoke those permissions. For example, the user may have a "help desk admin"
        role in Google, or a domain-admin in Active Directory.
      id: 0bf14e3e-fd58-4a0a-8a31-276f00e966bb
      iscommand: false
      name: Revoke administrative user roles
      type: regular
      version: -1
    taskid: 0bf14e3e-fd58-4a0a-8a31-276f00e966bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 720
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Set new passwords for the user to prevent unauthorized access.
        Store the new password somewhere safe.
      id: fa2b7f9b-ff3b-4232-8adc-488d82724ea4
      iscommand: false
      name: Set new passwords for the user
      type: regular
      version: -1
    taskid: fa2b7f9b-ff3b-4232-8adc-488d82724ea4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1190,
          "y": 720
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        Make sure that the user returned all company-property that was in their possession, such as company cell-phones, laptops, notebooks containing sensitive data, etc.
        Do not proceed until all property was returned.
      id: f18315e9-3c06-44df-8017-1f005dac422c
      iscommand: false
      name: Confirm retrieval of company property
      type: regular
      version: -1
    taskid: f18315e9-3c06-44df-8017-1f005dac422c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 900
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
      - "10"
      - "11"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 3d4b032b-8c7e-4058-859c-6eb13394d1fd
      iscommand: false
      name: Delegation
      type: title
      version: -1
    taskid: 3d4b032b-8c7e-4058-859c-6eb13394d1fd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1170
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Set an auto-reply message for the user in your preferred email
        client. State that the user will not be able to reply anymore and is leaving
        the company.
      id: e8ce2f3b-b0fd-459e-8d24-13f9bd4710d5
      iscommand: false
      name: Set auto-reply message for the user
      type: regular
      version: -1
    taskid: e8ce2f3b-b0fd-459e-8d24-13f9bd4710d5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -100,
          "y": 1320
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
      - "13"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Delegate access of the user's mailbox, calendar, file-sharing apps,
        and so on to their manager.
      id: f9ca9caf-9e7f-4000-801d-361b7cb102ad
      iscommand: false
      name: Delegate access to manager
      type: regular
      version: -1
    taskid: f9ca9caf-9e7f-4000-801d-361b7cb102ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1320
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Forward future emails from the user's mailbox to their manager's
        email.
      id: 0d3a7c86-221d-4d29-84b8-1a17739c9b57
      iscommand: false
      name: Forward emails to manager
      type: regular
      version: -1
    taskid: 0d3a7c86-221d-4d29-84b8-1a17739c9b57
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 1320
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Update the user's manager that the user's mailbox has been delegated
        to them, and that future incoming emails for the user will be redirected to
        them.
      id: a21d9e65-ae5d-4977-8e63-a03873ea836f
      iscommand: false
      name: Update manager about delegation and mail forwarding
      type: regular
      version: -1
    taskid: a21d9e65-ae5d-4977-8e63-a03873ea836f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 740,
          "y": 1540
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 4f0c0479-82a9-4840-8060-d6fce3a7ed6a
      iscommand: false
      name: Retention & Deletion
      type: title
      version: -1
    taskid: 4f0c0479-82a9-4840-8060-d6fce3a7ed6a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1780
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Backup important user emails, files and documents. Google Vault
        is one service that can be used for that.
      id: adcb5120-adab-4734-80a3-6bc4783dbbb6
      iscommand: false
      name: Copy, backup or download crucial user data
      type: regular
      version: -1
    taskid: adcb5120-adab-4734-80a3-6bc4783dbbb6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1930
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Disable the user in chat, management or other work applications.
        Most importantly, you should disable the user in your Single Source of Truth
        (SSOT) application, such as Active Directory.
      id: 8f167fcb-bb27-4ce3-84a4-007f30e85620
      iscommand: false
      name: Disable user in all applications
      type: regular
      version: -1
    taskid: 8f167fcb-bb27-4ce3-84a4-007f30e85620
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2090
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
      - "18"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Wait for a period of time, say 30 days, before proceeding to final
        removal of the user from the system.
      id: d3557332-714b-43e5-831a-a4fdd4ec409b
      iscommand: false
      name: Wait for 30 days
      type: regular
      version: -1
    taskid: d3557332-714b-43e5-831a-a4fdd4ec409b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2260
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Permanently delete previously-retained user information and files
      id: 81882f9f-24f9-4644-81d4-5e0e8b7ffabd
      iscommand: false
      name: Delete old user data
      type: regular
      version: -1
    taskid: 81882f9f-24f9-4644-81d4-5e0e8b7ffabd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 2460
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |-
        Delete the user from all applications used in your organization.
        Alternatively, you can move the user to an "old employees" group where you keep employees that left and apply certain restrictions to that group.
      id: 837a5d78-321a-4aae-8e78-06c135ec6379
      iscommand: false
      name: Delete the user
      type: regular
      version: -1
    taskid: 837a5d78-321a-4aae-8e78-06c135ec6379
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 790,
          "y": 2460
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    note: false
    reputationcalc: 1
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Closes the current incident.
      id: d601d031-c78a-4d50-88f2-65da8f1676a8
      iscommand: true
      name: Close offboarding incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d601d031-c78a-4d50-88f2-65da8f1676a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2720
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - "1"
    note: false
    scriptarguments:
      DatetimeToWaitUntil:
        complex:
          accessor: offboardingdate
          root: incident
    separatecontext: true
    task:
      brand: ""
      id: ccb80848-f4b8-4e87-8642-bea56ae8a7d7
      iscommand: false
      name: Wait Until Datetime
      playbookId: Wait Until Datetime
      type: playbook
      version: -1
    taskid: ccb80848-f4b8-4e87-8642-bea56ae8a7d7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2765,
        "width": 1860,
        "x": -290,
        "y": 50
      }
    }
  }
