description: This playbook runs Palo Alto Best Practice Assessment checks for a Panorama
  instance.
id: Run Panorama Best Practice Assessment
inputs: []
name: Run Panorama Best Practice Assessment
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 5515df32-fe99-44e2-89ae-11a2ef02fc6b
      iscommand: false
      name: ""
      version: -1
    taskid: 5515df32-fe99-44e2-89ae-11a2ef02fc6b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    separatecontext: false
    task:
      brand: BPA
      description: Submits a best practice assessment job.
      id: c1dc0301-faa5-49dc-8aed-1194ddf54c1f
      iscommand: true
      name: Submit BPA job
      script: BPA|||pan-os-bpa-submit-job
      type: regular
      version: -1
    taskid: c1dc0301-faa5-49dc-8aed-1194ddf54c1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${PAN-OS-BPA.SubmittedJob.JobID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: task_id
      PollingCommandName:
        simple: pan-os-bpa-get-job-results
      Timeout:
        simple: "10"
      dt:
        simple: PAN-OS-BPA.JobResults(val.Status!=='complete').JobID
    separatecontext: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: e3e8cd8b-0a04-4edb-8a07-ddf0c6c7c290
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: e3e8cd8b-0a04-4edb-8a07-ddf0c6c7c290
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    scriptarguments:
      task_id:
        simple: ${PAN-OS-BPA.SubmittedJob.JobID}
    separatecontext: false
    task:
      brand: BPA
      description: Returns results of the best practice assessment job.
      id: be5c533d-2bc9-45d9-8568-9500e69d6fd2
      iscommand: true
      name: Get BPA Results
      script: BPA|||pan-os-bpa-get-job-results
      type: regular
      version: -1
    taskid: be5c533d-2bc9-45d9-8568-9500e69d6fd2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 645,
        "width": 380,
        "x": 450,
        "y": 220
      }
    }
  }
