id: ee063efc-4902-417c-82d5-1ef651523220
inputs: []
name: Close Investigation
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 09f059dc-8539-493d-89e3-063231de0b24
      iscommand: false
      name: ""
      version: -1
    taskid: 09f059dc-8539-493d-89e3-063231de0b24
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: ${entries}
      closeReason: {}
      id: {}
    separatecontext: false
    task:
      brand: Builtin
      id: 585e33a1-2a83-48a1-87c9-0c55d89155c3
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 585e33a1-2a83-48a1-87c9-0c55d89155c3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: fcb53139-58ee-41b6-8550-4f43a7b2f621
      iscommand: false
      name: Please enter the reason why you're closing this...
      type: regular
      version: -1
    taskid: fcb53139-58ee-41b6-8550-4f43a7b2f621
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    scriptarguments:
      contextKey:
        simple: analystcomment
      entryId:
        simple: ${lastCompletedTaskEntries}
      extend-context:
        simple: closinguser=Metadata.user
      listSeperator: {}
    separatecontext: false
    task:
      brand: ""
      id: a2bfccf6-27a5-4fa2-8ffb-f1a027c785b3
      iscommand: false
      name: Retrieve comment and closing user id
      script: commentsToContext
      type: regular
      version: -1
    taskid: a2bfccf6-27a5-4fa2-8ffb-f1a027c785b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
