description: |-
  This playbook blocks Domains using Palo Alto Networks Panorama or Firewall External Dynamic Lists.
  It checks if the EDL configuration is in place with the 'PAN-OS EDL Setup' sub-playbook
  (otherwise the list will be configured), and adds the input Domains to the relevant lists.
id: PAN-OS - Block Domain - External Dynamic List
inputs:
- description: Domain to block
  key: Domain
  required: false
  value:
    complex:
      accessor: Name
      filters:
      - - left:
            iscontext: true
            value:
              simple: Domain.Malicious
          operator: isExists
      root: Domain
      transformers:
      - operator: uniq
- description: Domain list from the instance context with which to override the remote
    file.
  key: DomainListName
  required: false
  value:
    simple: Demisto Remediation - Domain EDL
- description: Log Forwarding object name.
  key: LogForwarding
  required: false
  value: {}
- description: EDL server IP address.
  key: EDLServerIP
  required: false
  value: {}
- description: |-
    This input establishes whether to commit the configuration automatically.
    Yes - Commit automatically.
    No - Commit manually.
  key: AutoCommit
  required: false
  value:
    simple: "No"
- description: Enter pre-rulebase or post-rulebase, according to the rule structure.
  key: pre-post-rulebase
  required: false
  value:
    simple: pre-rulebase
- description: |-
    The position of the rule in the ruleset. Valid values are:
      * Top
      * Bottom
      * Before
      * After
  key: rule-position
  required: false
  value: {}
name: PAN-OS - Block Domain - External Dynamic List
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 7144823f-b498-4a71-8d20-8836daf980e2
      iscommand: false
      name: ""
      version: -1
    taskid: 7144823f-b498-4a71-8d20-8836daf980e2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": -210
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 14e0cc74-3e4f-451a-819a-9f2a08b0b4d3
      iscommand: false
      name: Malicious Domains
      type: title
      version: -1
    taskid: 14e0cc74-3e4f-451a-819a-9f2a08b0b4d3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 707.5,
          "y": 100
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    scriptarguments:
      add_or_remove:
        simple: add
      file_path:
        complex:
          root: inputs.DomainListName
          transformers:
          - args:
              prefix: {}
              suffix:
                value:
                  simple: .txt
            operator: concat
      list_items:
        complex:
          root: inputs.Domain
          transformers:
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      list_name:
        complex:
          root: inputs.DomainListName
      verbose: {}
    separatecontext: false
    task:
      brand: ""
      description: Updates the instance context with the specified list name and list
        items, and overrides the path of the remote file with the internal list.
      id: 1095a8a8-bb7c-4011-8d15-eaa165df3db1
      iscommand: true
      name: PAN OS - Update Domain EDL
      script: '|||pan-os-edl-update'
      type: regular
      version: -1
    taskid: 1095a8a8-bb7c-4011-8d15-eaa165df3db1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 960,
          "y": 580
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    scriptarguments:
      device-group: {}
      name:
        complex:
          root: inputs.DomainListName
    separatecontext: false
    task:
      brand: ""
      description: Refreshes the specified external dynamic list
      id: af6ba305-dd7d-4ce1-8fe5-1dd39187ab96
      iscommand: true
      name: PAN-OS - Refresh Domain EDL
      script: '|||panorama-refresh-edl'
      type: regular
      version: -1
    taskid: af6ba305-dd7d-4ce1-8fe5-1dd39187ab96
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 960,
          "y": 1090
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 126ef010-3b9e-403b-8f7a-0a3e27fdf3d7
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 126ef010-3b9e-403b-8f7a-0a3e27fdf3d7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1260
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Domain
          operator: isNotEmpty
      label: "yes"
    id: "11"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "12"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: c0322d13-3a48-41c5-8e7c-3e77b8e4a79c
      iscommand: false
      name: Are there Domains to update?
      type: condition
      version: -1
    taskid: c0322d13-3a48-41c5-8e7c-3e77b8e4a79c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 707.5,
          "y": 240
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    scriptarguments:
      action-type:
        simple: drop
      auto-commit:
        complex:
          root: inputs.AutoCommit
      device-group: {}
      inbound-or-outbound-rule: {}
      ioc-type:
        simple: Domain
      list-name:
        complex:
          root: inputs.DomainListName
      log-forwarding-object-name:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.LogForwarding
              operator: isNotEmpty
          root: inputs.LogForwarding
      pre-post-rulebase:
        complex:
          root: inputs.pre-post-rulebase
      relative-rule-name: {}
      rule-name: {}
      rule-position:
        complex:
          root: inputs.rule-position
      web-server-ip:
        complex:
          root: inputs.EDLServerIP
    separatecontext: true
    task:
      brand: ""
      description: Sets up an external dynamic list in PAN-OS.\n If the file exists
        on the web server, it will sync it to Demisto. Lastly, it will create an EDL
        object and a matching rule.
      id: fcd76346-8f56-4df1-82cd-9bb40e24abda
      iscommand: false
      name: PAN-OS EDL Setup
      playbookId: PAN-OS EDL Setup
      type: playbook
      version: -1
    taskid: fcd76346-8f56-4df1-82cd-9bb40e24abda
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 960,
          "y": 410
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: palo_alto_networks_pan_os_edl_management
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "14"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 0390aedf-db29-4159-8ee7-e2f83dbddefa
      iscommand: false
      name: Is Palo Alto Networks PAN-OS EDL Management Enabled?
      type: condition
      version: -1
    taskid: 0390aedf-db29-4159-8ee7-e2f83dbddefa
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": -70
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: panorama.model
          operator: isEqualString
          right:
            value:
              simple: Panorama
      label: "yes"
    id: "15"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "9"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 38da7cf3-84fe-4d4d-85cb-9850815a20d3
      iscommand: false
      name: Is the instance type Panorama?
      type: condition
      version: -1
    taskid: 38da7cf3-84fe-4d4d-85cb-9850815a20d3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 960,
          "y": 910
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    scriptarguments:
      action: {}
      category: {}
      cmd:
        simple: <show><system><info></info></system></show>
      command: {}
      dst: {}
      element: {}
      extend-context:
        simple: panorama.model=response.result.system.model
      from: {}
      job-id: {}
      key: {}
      log-type: {}
      pcap-id: {}
      period: {}
      query: {}
      reportname: {}
      reporttype: {}
      search-time: {}
      serialno: {}
      target: {}
      to: {}
      type:
        simple: op
      where: {}
      xpath: {}
    separatecontext: false
    task:
      brand: ""
      description: Run any command supported in the API.
      id: 25857a23-4e34-425c-868e-310fdc1a7a5f
      iscommand: true
      name: Fetch instance info
      script: '|||panorama'
      type: regular
      version: -1
    taskid: 25857a23-4e34-425c-868e-310fdc1a7a5f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 960,
          "y": 750
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_9_#default#": 0.19,
      "14_9_#default#": 0.21
    },
    "paper": {
      "dimensions": {
        "height": 1535,
        "width": 952.5,
        "x": 387.5,
        "y": -210
      }
    }
  }
