id: f8604726-8a77-4720-8b51-3748f72c7839
inputs: []
name: Whois_test
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: a9e9631c-214a-4dcf-8b72-8031a526e890
      iscommand: false
      name: ""
      version: -1
    taskid: a9e9631c-214a-4dcf-8b72-8031a526e890
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    scriptarguments:
      query:
        simple: google.com
    separatecontext: false
    task:
      brand: Whois
      description: Provides data enrichment for domains.
      id: 1d8ce88c-a49b-4933-8d26-120f1e2a8153
      iscommand: true
      name: who is
      script: Whois|||whois
      type: regular
      version: -1
    taskid: 1d8ce88c-a49b-4933-8d26-120f1e2a8153
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
