id: 78dd6471-1166-4fef-8439-1579d24ebe48
inputs: []
name: File_Write
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: ff558437-21d6-4af0-8690-9372837e2260
      iscommand: false
      name: ""
      version: -1
    taskid: ff558437-21d6-4af0-8690-9372837e2260
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -30
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    scriptarguments:
      file:
        simple: ${incident.details}
      system: {}
      timeout: {}
    separatecontext: false
    task:
      brand: remoteaccess
      id: 97479926-0731-4ec1-87b6-6cc121d34c98
      iscommand: true
      name: Fetch File from Remote Machine
      script: remoteaccess|||copy-from
      type: regular
      version: -1
    taskid: 97479926-0731-4ec1-87b6-6cc121d34c98
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 90
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    task:
      brand: Builtin
      id: 4ce79010-3d9c-492d-8d9a-d03cf06f1405
      iscommand: true
      name: Close the Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4ce79010-3d9c-492d-8d9a-d03cf06f1405
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: d277c422-5046-4bd3-8fd5-37df869f1ef3
      iscommand: false
      name: Get Data for the File
      type: regular
      version: -1
    taskid: d277c422-5046-4bd3-8fd5-37df869f1ef3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 420
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    scriptarguments:
      dest-dir:
        simple: /home/ec2-user
      entry: {}
      fileID:
        simple: ${File.EntryID}
      system: {}
      timeout: {}
    separatecontext: false
    task:
      brand: remoteaccess
      id: 14ab6110-0212-43fd-8fb4-6289c0009156
      iscommand: true
      name: Write to Remote Machine
      script: remoteaccess|||copy-to
      type: regular
      version: -1
    taskid: 14ab6110-0212-43fd-8fb4-6289c0009156
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 930
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    scriptarguments:
      data:
        simple: '${FileData} ${FileContents} '
      entryId: {}
      filename:
        simple: ${incident.details}
    separatecontext: false
    task:
      brand: ""
      id: e3b9118a-706d-4544-8b1d-7f860ec23330
      iscommand: false
      name: Write Content to File
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: e3b9118a-706d-4544-8b1d-7f860ec23330
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 750
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ""
      id: 469ec44c-231f-443d-886c-7a920cffdf70
      iscommand: false
      name: Read the File Contents
      script: ReadFile
      type: regular
      version: -1
    taskid: 469ec44c-231f-443d-886c-7a920cffdf70
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 245
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    scriptarguments:
      contextKey:
        simple: FileContents
      entryId:
        simple: ${lastCompletedTaskEntries}
      listSeperator: {}
    separatecontext: false
    task:
      brand: ""
      id: 888fde01-53ad-4085-82e9-39a2aef33e6e
      iscommand: false
      name: Add User given File Content to Context
      script: commentsToContext
      type: regular
      version: -1
    taskid: 888fde01-53ad-4085-82e9-39a2aef33e6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 575
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1235,
        "width": 380,
        "x": 450,
        "y": -30
      }
    }
  }
