description: |-
  Detonates a File using the Symantec Blue Coat Content and Malware Analysis.
  Advanced Threat Defense supports the following File Types:
  Microsoft (2003 and earlier)
  doc, dot, xls, csv, xlt, xlm, ppt, pot, pps

  Microsoft (2007 and later):
  docx, docm, dotx, dotm, dotm, xlsx, xlsm, xltx, xltm, xlsb, xla, xlam, iqy, pptx, pptm, potx, ppsx, xml

  Other:
  pe32, rtf, pdf, vbs, vbe, ps1, js, lnk, html, bat
id: Detonate URL - Symantec Blue Coat Content and Malware Analysis Beta
inputs:
- description: The URL to detonate.
  key: URL
  required: false
  value: {}
- description: How much time to wait before a timeout occurs (seconds).
  key: Timeout
  required: false
  value:
    simple: "300"
name: Detonate URL - Symantec Blue Coat Content and Malware Analysis Beta
outputs:
- contextPath: DBotScore.Vendor
  description: The name of the vendor.
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator of the score.
  type: string
- contextPath: DBotScore.Type
  description: The type for the score. For example, Email.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
- contextPath: DBotScore.Malicious.Vendor
  description: The name of the vendor.
  type: string
- contextPath: DBotScore.Malicious.Detections
  description: The sub analysis detection statuses.
  type: string
- contextPath: DBotScore.Malicious.SHA1
  description: The SHA1 of the file.
  type: string
- contextPath: InfoFile.Name
  description: The name of the file.
  type: string
- contextPath: InfoFile.EntryID
  description: The entry ID of the report.
  type: string
- contextPath: InfoFile.Size
  description: The size of the file.
  type: number
- contextPath: InfoFile.Type
  description: The type of the file. For example, "PE".
  type: string
- contextPath: InfoFile.Info
  description: Basic information of the file.
  type: string
- contextPath: InfoFile.Extension
  description: The extension of the file.
  type: string
- contextPath: File.Size
  description: The size of the file.
  type: number
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
  type: string
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
  type: string
- contextPath: File.Name
  description: The name of the sample file.
  type: string
- contextPath: File.SSDeep
  description: The SSDeep hash of the file.
  type: string
- contextPath: File.EntryID
  description: The War Room entry ID of the file.
  type: string
- contextPath: File.Info
  description: Basic information of the file.
  type: string
- contextPath: File.Type
  description: The type of the file. For example, "PE".
  type: string
- contextPath: File MD5
  description: The MD5 hash of the file.
  type: string
- contextPath: File.Extension
  description: The extension of the file.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: '-'
      id: 489b704c-bef9-40e7-8aa8-f74cca308a94
      iscommand: false
      name: ""
      version: -1
    taskid: 489b704c-bef9-40e7-8aa8-f74cca308a94
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ""
      description: finished
      id: e589b774-3cee-4dff-8e14-788ef3590dfa
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e589b774-3cee-4dff-8e14-788ef3590dfa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 70,
          "y": 1945
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Symantec Blue Coat Content and Malware Analysis
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "7"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "15"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: |
        Verify whether there is a valid instance of Symantec Blue Coat Malware Analysis enabled.
      id: 98905212-e1cc-4563-8dba-c6587d631a0c
      iscommand: false
      name: Is SCMA enabled?
      type: condition
      version: -1
    taskid: 98905212-e1cc-4563-8dba-c6587d631a0c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 335
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    scriptarguments:
      task_id:
        complex:
          accessor: Analysis.ID
          root: Symantec
    separatecontext: false
    task:
      brand: ""
      description: Retrieves a detonation report.
      id: a2d1eb58-d074-4fe2-8d96-f7f04a9a4f77
      iscommand: true
      name: SCMA Get Info
      script: '|||symantec-cma-get-report'
      type: regular
      version: -1
    taskid: a2d1eb58-d074-4fe2-8d96-f7f04a9a4f77
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1225
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    scriptarguments:
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    task:
      brand: ""
      description: Submit a URL for analysis.
      id: 7d61b459-e783-4d52-8c96-98cfb83c0bb5
      iscommand: true
      name: SCMA Detonate URL
      script: '|||symantec-cma-upload-url'
      type: regular
      version: -1
    taskid: 7d61b459-e783-4d52-8c96-98cfb83c0bb5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 895
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    scriptarguments:
      seconds:
        complex:
          root: inputs.Timeout
    separatecontext: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 35997039-274c-4c2e-849f-2d6d3ab3f261
      iscommand: false
      name: sleep 5 minutes
      script: Sleep
      type: regular
      version: -1
    taskid: 35997039-274c-4c2e-849f-2d6d3ab3f261
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 390,
          "y": 1050
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1960,
        "width": 720,
        "x": 50,
        "y": 50
      }
    }
  }
