description: Default playbook for parsing Prisma Cloud Compute audit alerts
id: Prisma Cloud Compute - Audit Alert
inputs: []
name: Prisma Cloud Compute - Audit Alert
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: db3ae054-8893-4760-871f-9e39c7439d6c
      iscommand: false
      name: ""
      version: -1
    taskid: db3ae054-8893-4760-871f-9e39c7439d6c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    scriptarguments:
      alert_raw_json:
        simple: ${incident.prismacloudcomputerawalertjson}
    separatecontext: false
    task:
      brand: ""
      description: Parse raw vulnerabilities JSON data
      id: 360f5aa0-896d-4ec2-8678-d4b2d0de15f6
      iscommand: false
      name: Parse Audit Alert
      script: PrismaCloudComputeParseAuditAlert
      type: regular
      version: -1
    taskid: 360f5aa0-896d-4ec2-8678-d4b2d0de15f6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
