description: |-
  This playbook remediates the following Prisma Cloud AWS IAM password policy alerts.

  Prisma Cloud policies remediated:
  - AWS IAM password policy allows password reuse
  - AWS IAM password policy does not expire in 90 days
  - AWS IAM password policy does not have a lowercase character
  - AWS IAM password policy does not have a minimum of 14 characters
  - AWS IAM password policy does not have a number
  - AWS IAM password policy does not have a symbol
  - AWS IAM password policy does not have a uppercase character
  - AWS IAM password policy does not have password expiration period
  - AWS IAM Password policy is insecure
id: Prisma Cloud Remediation - AWS IAM Password Policy Misconfiguration
inputs:
- description: Get the Prisma Cloud policy ID.
  key: policyId
  required: true
  value: {}
name: Prisma Cloud Remediation - AWS IAM Password Policy Misconfiguration
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 972c2cba-e9e8-4b4e-8f92-407ca7fb7917
      iscommand: false
      name: ""
      version: -1
    taskid: 972c2cba-e9e8-4b4e-8f92-407ca7fb7917
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 690,
          "y": -180
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge: {}
      minimumPasswordLength: {}
      passwordReusePrevention:
        simple: "5"
      requireLowercaseCharacters: {}
      requireNumbers: {}
      requireSymbols: {}
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to prevent password reuse.
      id: 1541a3a0-b8c0-460e-893a-96c8fc75ecc6
      iscommand: true
      name: Remediate IAM password policy allows password reuse
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: 1541a3a0-b8c0-460e-893a-96c8fc75ecc6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 140
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: a2107824-6ed5-4c67-9450-8b154bb1fd2b
      label: password reuse
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: f53107a2-00b2-46fb-98a9-1f12262c7d44
      label: expire in 90 days
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: ef7c537b-72eb-42a7-bab7-cb2d22c76a0d
      label: require lowercase
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: 168bfaa0-8c1d-427e-bfa8-4d96d82e3d83
      label: minimum length
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: 9a5813af-17a3-4058-be13-588ea00b4bfa
      label: require numbers
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: fd4dae57-509e-4374-96d3-e136821fc3f3
      label: require symbol
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: 31626ca9-f659-4d25-9d88-fa32262bbba7
      label: require uppercase
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: a8dcc272-0b02-4534-8627-cf70ddd264c5
      label: expiration period
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.policyId
          operator: isEqualString
          right:
            value:
              simple: b1acdeff-4959-4c14-8a5e-2adc1016a3d5
      label: policy insecure
    id: "10"
    ignoreworker: false
    nexttasks:
      expiration period:
      - "17"
      expire in 90 days:
      - "11"
      minimum length:
      - "13"
      password reuse:
      - "4"
      policy insecure:
      - "18"
      require lowercase:
      - "12"
      require numbers:
      - "14"
      require symbol:
      - "15"
      require uppercase:
      - "16"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Based on the Prisma Cloud policy ID, determine which IAM password
        policy attribute to remediate.
      id: 68839924-ec0e-4ed5-8810-420713a772ba
      iscommand: false
      name: Get Prisma Cloud policy id
      type: condition
      version: -1
    taskid: 68839924-ec0e-4ed5-8810-420713a772ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": -30
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge:
        simple: "90"
      minimumPasswordLength: {}
      passwordReusePrevention: {}
      requireLowercaseCharacters: {}
      requireNumbers: {}
      requireSymbols: {}
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that passwords expire
        after 90 days.
      id: c2fa1f1a-a03e-4e1c-8a09-6945b6724261
      iscommand: true
      name: Remediate IAM password policy does not expire in 90 days
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: c2fa1f1a-a03e-4e1c-8a09-6945b6724261
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 310
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge: {}
      minimumPasswordLength: {}
      passwordReusePrevention: {}
      requireLowercaseCharacters:
        simple: "True"
      requireNumbers: {}
      requireSymbols: {}
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that the password
        must contain at least one lowercase character.
      id: ad4c2820-7478-4c35-8d42-d0e7d3b15e36
      iscommand: true
      name: Remediate AWS IAM password policy does not have a lowercase character
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: ad4c2820-7478-4c35-8d42-d0e7d3b15e36
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -70,
          "y": 480
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge: {}
      minimumPasswordLength:
        simple: "14"
      passwordReusePrevention: {}
      requireLowercaseCharacters: {}
      requireNumbers: {}
      requireSymbols: {}
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to verify that the password
        contains at least 14 characters.
      id: 0068d356-a8c1-44bc-8374-493ae525bfcd
      iscommand: true
      name: Remediate AWS IAM password policy does not have a minimum of 14 characters
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: 0068d356-a8c1-44bc-8374-493ae525bfcd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -260,
          "y": 640
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge: {}
      minimumPasswordLength: {}
      passwordReusePrevention: {}
      requireLowercaseCharacters: {}
      requireNumbers:
        simple: "True"
      requireSymbols: {}
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that the password
        includes at least one number.
      id: 96fb3a21-c45b-46aa-8583-b47fbff4c7dd
      iscommand: true
      name: Remediate AWS IAM password policy does not have a number
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: 96fb3a21-c45b-46aa-8583-b47fbff4c7dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 310
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge: {}
      minimumPasswordLength: {}
      passwordReusePrevention: {}
      requireLowercaseCharacters: {}
      requireNumbers: {}
      requireSymbols:
        simple: "True"
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that the password
        contains at least one special character.
      id: dc3dde5a-d558-4377-8287-beb786e40d47
      iscommand: true
      name: Remediate AWS IAM password policy does not have a symbol
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: dc3dde5a-d558-4377-8287-beb786e40d47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1070,
          "y": 140
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge: {}
      minimumPasswordLength: {}
      passwordReusePrevention: {}
      requireLowercaseCharacters: {}
      requireNumbers: {}
      requireSymbols: {}
      requireUppercaseCharacters:
        simple: "True"
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that the password
        contains at least one uppercase character.
      id: 94b6b908-ee21-465c-8497-ba8b6d33735e
      iscommand: true
      name: Remediate AWS IAM password policy does not have a uppercase character
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: 94b6b908-ee21-465c-8497-ba8b6d33735e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1260,
          "y": 310
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword: {}
      hardExpiry: {}
      maxPasswordAge:
        simple: "90"
      minimumPasswordLength: {}
      passwordReusePrevention: {}
      requireLowercaseCharacters: {}
      requireNumbers: {}
      requireSymbols: {}
      requireUppercaseCharacters: {}
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that the password
        includes an expiration date.
      id: 6655d3a8-af50-4d86-839e-308aaa458346
      iscommand: true
      name: Remediate AWS IAM password policy does not have password expiration period
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: 6655d3a8-af50-4d86-839e-308aaa458346
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1450,
          "y": 480
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    scriptarguments:
      allowUsersToChangePassword:
        simple: "True"
      hardExpiry:
        simple: "True"
      maxPasswordAge:
        simple: "90"
      minimumPasswordLength:
        simple: "14"
      passwordReusePrevention:
        simple: "4"
      requireLowercaseCharacters:
        simple: "True"
      requireNumbers:
        simple: "True"
      requireSymbols:
        simple: "True"
      requireUppercaseCharacters:
        simple: "True"
    separatecontext: false
    task:
      brand: ""
      description: Create or update a password policy to ensure that there are no
        insecure passwords.
      id: 466538d1-57bc-4aec-872e-2192b24de9df
      iscommand: true
      name: Remediate AWS IAM Password policy is insecure
      script: '|||aws-iam-update-account-password-policy'
      type: regular
      version: -1
    taskid: 466538d1-57bc-4aec-872e-2192b24de9df
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1640,
          "y": 640
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ""
      id: f688c628-328d-4db0-870f-2012cdb397b4
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f688c628-328d-4db0-870f-2012cdb397b4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 690,
          "y": 810
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_11_expire in 90 days": 0.84,
      "10_12_require lowercase": 0.87,
      "10_13_minimum length": 0.9,
      "10_14_require numbers": 0.9,
      "10_16_require uppercase": 0.82,
      "10_17_expiration period": 0.87,
      "10_18_policy insecure": 0.9,
      "10_4_password reuse": 0.74
    },
    "paper": {
      "dimensions": {
        "height": 1055,
        "width": 2280,
        "x": -260,
        "y": -180
      }
    }
  }
