id: 071a1fc8-0e35-4632-85b7-072b761da72a
inputs:
- description: ""
  key: Input
  required: false
  value:
    simple: ${incident.name}
name: Sub Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: fff4f74a-413c-4adf-89c7-2ffd3f821c79
      iscommand: false
      name: ""
      version: -1
    taskid: fff4f74a-413c-4adf-89c7-2ffd3f821c79
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: ${inputs.Input}
    separatecontext: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 2bc29cb9-0163-4e82-8042-1fe6d03faa39
      iscommand: false
      name: 'Print '
      script: Print
      type: regular
      version: -1
    taskid: 2bc29cb9-0163-4e82-8042-1fe6d03faa39
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
